version: '3'

services:
  postgres:
    image: postgres:14
    container_name: rentacars-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: renta-car-db_owner
      POSTGRES_PASSWORD: id7m3oMJIXqK
      POSTGRES_DB: renta-car-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rentacars-nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://renta-car-db_owner:id7m3oMJIXqK@postgres:5432/renta-car-db
      - NEXT_PUBLIC_FRONTEND_STORE_URL=http://localhost:3000
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_aGVhbHRoeS1weXRob24tNDEuY2xlcmsuYWNjb3VudHMuZGV2JA
      - CLERK_SECRET_KEY=sk_test_MycfQOCJuC4bADrggOVb8h8qGT54F6tHy6axjtPDRI
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - UPLOADTHING_TOKEN=eyJhcGlLZXkiOiJza19saXZlXzY5NTk1N2Y1NDgzYmQ1NWU4OTQ5ZjBmODhlMGNhOWYzOTU2MTQ0MGM0OWM4ODU3ODAxYTk2MzIzNTg2MDBkOTUiLCJhcHBJZCI6InVjdWZicWkydHIiLCJyZWdpb25zIjpbInNlYTEiXX0=
      - NEXT_PUBLIC_ADMINISTRATOR=user_2oammORrO3tiBxUx5uhtR3pg1t0
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge